name: CI

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install deps
      run: sudo apt-get install -y colorized-logs

    - name: Build
      run: dotnet build -c Release

    - name: Solve all
      run: |
        dotnet run -c Release --no-build --project=AdventOfCode/src -- all
        cat results_log >> $GITHUB_STEP_SUMMARY
